apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  database_password: "{{.Values.dbpassword}}"
  database_root_password: "{{.Values.dbrootpassword}}"