apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: {{ .Values.namespace }}
data:
  database_host: mysql-service
  database_port: "3306"
  database_user: {{ .Values.dbuser }}