{{- if .Values.phpmyadminisdeployed}}
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: {{.Values.namespace}}
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: phpmyadmin
{{- end}}