apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
  namespace: laravel
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "C:\\Users\\plopez\\Documents\\Github\\kubernetes-weekly-exercise-second-ploopez\\soluciones\\storage"
    